name: Say hello

on:
  push:
    branches: [ 'main' ]
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Check out files
        run: |
          echo "$ echo ""Hello"""
          echo "Hello"
          echo $ ls -la 
          ls -la 
          echo $ pwd
          pwd
      - name: Install pytest
        run: |
          echo "$ pip install pytest"
          pip install pytest
          echo "$ pytest --version"
          pytest --version
