name: Say hello

on:
  #push:
  #  branches: [ 'main' ]
  workflow_dispatch:

jobs:
  say_hello:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v2
      - name: Check out files
        run: |
          echo "Hello"
          ls -la 
          pwd
